
/* File generated by gen_cfile.py. Should not be modified. */

#include "ObjDict2.h"

/**************************************************************************/
/* Declaration of the mapped variables                                    */
/**************************************************************************/
UNS8 DI11 = 0x20;		/* Mapped at index 0x2000, subindex 0x00 */
UNS8 DI21 = 0x40;		/* Mapped at index 0x2001, subindex 0x00 */
UNS32 DO11 = 0x88;		/* Mapped at index 0x2100, subindex 0x00 */
UNS8 DO21 = 0x80;		/* Mapped at index 0x2101, subindex 0x00 */

/**************************************************************************/
/* Declaration of the value range types                                   */
/**************************************************************************/

#define valueRange_EMC 0x9F /* Type for index 0x1003 subindex 0x00 (only set of value 0 is possible) */
UNS32 ObjDict2_valueRangeTest (UNS8 typeValue, void * value)
{
  switch (typeValue) {
    case valueRange_EMC:
      if (*(UNS8*)value != (UNS8)0) return OD_VALUE_RANGE_EXCEEDED;
      break;
  }
  return 0;
}

/**************************************************************************/
/* The node id                                                            */
/**************************************************************************/
/* node_id default value.*/
UNS8 ObjDict2_bDeviceNodeId = 0x09;

/**************************************************************************/
/* Array of message processing information */

const UNS8 ObjDict2_iam_a_slave = 1;

TIMER_HANDLE ObjDict2_heartBeatTimers[1] = {TIMER_NONE};

/*
$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$

                               OBJECT DICTIONARY

$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
*/

/* index 0x1000 :   Device Type. */
                    UNS32 ObjDict2_obj1000 = 0x12345;	/* 197009 */
                    subindex ObjDict2_Index1000[] = 
                     {
                       { RO, uint32, sizeof (UNS32), (void*)&ObjDict2_obj1000 }
                     };

/* index 0x1001 :   Error Register. */
                    UNS8 ObjDict2_obj1001 = 0x0;	/* 0 */
                    subindex ObjDict2_Index1001[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&ObjDict2_obj1001 }
                     };

/* index 0x1003 :   Pre-defined Error Field */
                    UNS8 ObjDict2_highestSubIndex_obj1003 = 0; /* number of subindex - 1*/
                    UNS32 ObjDict2_obj1003[] = 
                    {
                      0x0	/* 0 */
                    };
                    ODCallback_t ObjDict2_Index1003_callbacks[] = 
                     {
                       NULL,
                       NULL,
                     };
                    subindex ObjDict2_Index1003[] = 
                     {
                       { RW, valueRange_EMC, sizeof (UNS8), (void*)&ObjDict2_highestSubIndex_obj1003 },
                       { RO, uint32, sizeof (UNS32), (void*)&ObjDict2_obj1003[0] }
                     };

/* index 0x1005 :   SYNC COB ID. */
                    UNS32 ObjDict2_obj1005 = 0x40000080;	/* 1073741952 */
                    ODCallback_t ObjDict2_Index1005_callbacks[] = 
                     {
                       NULL,
                     };
                    subindex ObjDict2_Index1005[] = 
                     {
                       { RW, uint32, sizeof (UNS32), (void*)&ObjDict2_obj1005 }
                     };

/* index 0x1006 :   Communication / Cycle Period. */
                    //UNS32 ObjDict_obj1006 = 0xF4240;	/* 1000000 */
					UNS32 ObjDict2_obj1006 = 1000000;
                    ODCallback_t ObjDict2_Index1006_callbacks[] = 
                     {
                       NULL,
                     };
                    subindex ObjDict2_Index1006[] = 
                     {
                       { RW, uint32, sizeof (UNS32), (void*)&ObjDict2_obj1006 }
                     };

/* index 0x1014 :   Emergency COB ID */
                    UNS32 ObjDict2_obj1014 = 0x0;   /* 0 */

/* index 0x1016 :   Consumer Heartbeat Time. */
                    UNS8 ObjDict2_highestSubIndex_obj1016 = 1; /* number of subindex - 1*/
                    UNS32 ObjDict2_obj1016[] = 
                    {
                      0x4005DC	/* 4195804 */
                    };
                    subindex ObjDict2_Index1016[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&ObjDict2_highestSubIndex_obj1016 },
                       { RW, uint32, sizeof (UNS32), (void*)&ObjDict2_obj1016[0] }
                     };

/* index 0x1017 :   Producer Heartbeat Time */ 
                    UNS16 ObjDict2_obj1017 = 0x0;   /* 0 */

/* index 0x1018 :   Identity. */
                    UNS8 ObjDict2_highestSubIndex_obj1018 = 4; /* number of subindex - 1*/
                    UNS32 ObjDict2_obj1018_Vendor_ID = 0x1;	/* 0 */
                    UNS32 ObjDict2_obj1018_Product_Code = 0x2;	/* 0 */
                    UNS32 ObjDict2_obj1018_Revision_Number = 0x3;	/* 0 */
                    UNS32 ObjDict2_obj1018_Serial_Number = 0x4;	/* 0 */
                    subindex ObjDict2_Index1018[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&ObjDict2_highestSubIndex_obj1018 },
                       { RO, uint32, sizeof (UNS32), (void*)&ObjDict2_obj1018_Vendor_ID },
                       { RO, uint32, sizeof (UNS32), (void*)&ObjDict2_obj1018_Product_Code },
                       { RO, uint32, sizeof (UNS32), (void*)&ObjDict2_obj1018_Revision_Number },
                       { RO, uint32, sizeof (UNS32), (void*)&ObjDict2_obj1018_Serial_Number }
                     };

/* index 0x1200 :   Server SDO Parameter. */
                    UNS8 ObjDict2_highestSubIndex_obj1200 = 2; /* number of subindex - 1*/
                    UNS32 ObjDict2_obj1200_COB_ID_Client_to_Server_Receive_SDO = 0x609;	/* 1536 */
                    UNS32 ObjDict2_obj1200_COB_ID_Server_to_Client_Transmit_SDO = 0x589;	/* 1408 */
                    subindex ObjDict2_Index1200[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&ObjDict2_highestSubIndex_obj1200 },
                       { RO, uint32, sizeof (UNS32), (void*)&ObjDict2_obj1200_COB_ID_Client_to_Server_Receive_SDO },
                       { RO, uint32, sizeof (UNS32), (void*)&ObjDict2_obj1200_COB_ID_Server_to_Client_Transmit_SDO }
                     };

/* index 0x1280 :   Client SDO 1 Parameter. */
                    UNS8 ObjDict2_highestSubIndex_obj1280 = 3; /* number of subindex - 1*/
                    UNS32 ObjDict2_obj1280_COB_ID_Client_to_Server_Transmit_SDO = 0x606;	/* 1600 */
                    UNS32 ObjDict2_obj1280_COB_ID_Server_to_Client_Receive_SDO = 0x586;	/* 1472 */
                    UNS8 ObjDict2_obj1280_Node_ID_of_the_SDO_Server = 0x06;	/* 5 */
                    subindex ObjDict2_Index1280[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&ObjDict2_highestSubIndex_obj1280 },
                       { RW, uint32, sizeof (UNS32), (void*)&ObjDict2_obj1280_COB_ID_Client_to_Server_Transmit_SDO },
                       { RW, uint32, sizeof (UNS32), (void*)&ObjDict2_obj1280_COB_ID_Server_to_Client_Receive_SDO },
                       { RW, uint8, sizeof (UNS8), (void*)&ObjDict2_obj1280_Node_ID_of_the_SDO_Server }
                     };

/* index 0x1400 :   Receive PDO 1 Parameter. */
                    UNS8 ObjDict2_highestSubIndex_obj1400 = 5; /* number of subindex - 1*/
                    UNS32 ObjDict2_obj1400_COB_ID_used_by_PDO = 0x182;	/* 385 */
                    UNS8 ObjDict2_obj1400_Transmission_Type = 0x1;	/* 1 */
                    UNS16 ObjDict2_obj1400_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 ObjDict2_obj1400_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 ObjDict2_obj1400_Event_Timer = 0x0;	/* 0 */
                    subindex ObjDict2_Index1400[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&ObjDict2_highestSubIndex_obj1400 },
                       { RW, uint32, sizeof (UNS32), (void*)&ObjDict2_obj1400_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&ObjDict2_obj1400_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&ObjDict2_obj1400_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&ObjDict2_obj1400_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&ObjDict2_obj1400_Event_Timer }
                     };

/* index 0x1600 :   Receive PDO 1 Mapping. */
                    UNS8 ObjDict2_highestSubIndex_obj1600 = 1; /* number of subindex - 1*/
                    UNS32 ObjDict2_obj1600[] = 
                    {
                      0x20000008	/* 536870920 */
                    };
                    subindex ObjDict2_Index1600[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&ObjDict2_highestSubIndex_obj1600 },
                       { RW, uint32, sizeof (UNS32), (void*)&ObjDict2_obj1600[0] }
                     };

/* index 0x1800 :   Transmit PDO 1 Parameter. */
                    UNS8 ObjDict2_highestSubIndex_obj1800 = 5; /* number of subindex - 1*/
                    UNS32 ObjDict2_obj1800_COB_ID_used_by_PDO = 0x202;	/* 513 */
                    UNS8 ObjDict2_obj1800_Transmission_Type = 0x04;	/* 255 */
                    UNS16 ObjDict2_obj1800_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 ObjDict2_obj1800_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 ObjDict2_obj1800_Event_Timer = 0x0;	/* 0 */
                    ODCallback_t ObjDict2_Index1800_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                     };
                    subindex ObjDict2_Index1800[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&ObjDict2_highestSubIndex_obj1800 },
                       { RW, uint32, sizeof (UNS32), (void*)&ObjDict2_obj1800_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&ObjDict2_obj1800_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&ObjDict2_obj1800_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&ObjDict2_obj1800_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&ObjDict2_obj1800_Event_Timer }
                     };

/* index 0x1A00 :   Transmit PDO 1 Mapping. */
                    UNS8 ObjDict2_highestSubIndex_obj1A00 = 1; /* number of subindex - 1*/
                    UNS32 ObjDict2_obj1A00[] = 
                    {
                      0x21000008	/* 553648136 */
                    };
                    subindex ObjDict2_Index1A00[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&ObjDict2_highestSubIndex_obj1A00 },
                       { RW, uint32, sizeof (UNS32), (void*)&ObjDict2_obj1A00[0] }
                     };

/* index 0x2000 :   Mapped variable DI1 */
                    subindex ObjDict2_Index2000[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&DI11 }
                     };

/* index 0x2001 :   Mapped variable DI2 */
                    subindex ObjDict2_Index2001[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&DI21 }
                     };

/* index 0x2100 :   Mapped variable DO1 */
                    subindex ObjDict2_Index2100[] = 
                     {
                       { RW, uint32, sizeof (UNS32), (void*)&DO11 }
                     };

/* index 0x2101 :   Mapped variable DO2 */
                    subindex ObjDict2_Index2101[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&DO21 }
                     };

const indextable ObjDict2_objdict[] = 
{
  { (subindex*)ObjDict2_Index1000,sizeof(ObjDict2_Index1000)/sizeof(ObjDict2_Index1000[0]), 0x1000},
  { (subindex*)ObjDict2_Index1001,sizeof(ObjDict2_Index1001)/sizeof(ObjDict2_Index1001[0]), 0x1001},
  { (subindex*)ObjDict2_Index1005,sizeof(ObjDict2_Index1005)/sizeof(ObjDict2_Index1005[0]), 0x1005},
  { (subindex*)ObjDict2_Index1006,sizeof(ObjDict2_Index1006)/sizeof(ObjDict2_Index1006[0]), 0x1006},
  { (subindex*)ObjDict2_Index1016,sizeof(ObjDict2_Index1016)/sizeof(ObjDict2_Index1016[0]), 0x1016},
  { (subindex*)ObjDict2_Index1018,sizeof(ObjDict2_Index1018)/sizeof(ObjDict2_Index1018[0]), 0x1018},
  { (subindex*)ObjDict2_Index1200,sizeof(ObjDict2_Index1200)/sizeof(ObjDict2_Index1200[0]), 0x1200},
  { (subindex*)ObjDict2_Index1280,sizeof(ObjDict2_Index1280)/sizeof(ObjDict2_Index1280[0]), 0x1280},
  { (subindex*)ObjDict2_Index1400,sizeof(ObjDict2_Index1400)/sizeof(ObjDict2_Index1400[0]), 0x1400},
  { (subindex*)ObjDict2_Index1600,sizeof(ObjDict2_Index1600)/sizeof(ObjDict2_Index1600[0]), 0x1600},
  { (subindex*)ObjDict2_Index1800,sizeof(ObjDict2_Index1800)/sizeof(ObjDict2_Index1800[0]), 0x1800},
  { (subindex*)ObjDict2_Index1A00,sizeof(ObjDict2_Index1A00)/sizeof(ObjDict2_Index1A00[0]), 0x1A00},
  { (subindex*)ObjDict2_Index2000,sizeof(ObjDict2_Index2000)/sizeof(ObjDict2_Index2000[0]), 0x2000},
  { (subindex*)ObjDict2_Index2001,sizeof(ObjDict2_Index2001)/sizeof(ObjDict2_Index2001[0]), 0x2001},
  { (subindex*)ObjDict2_Index2100,sizeof(ObjDict2_Index2100)/sizeof(ObjDict2_Index2100[0]), 0x2100},
  { (subindex*)ObjDict2_Index2101,sizeof(ObjDict2_Index2101)/sizeof(ObjDict2_Index2101[0]), 0x2101},
};

const indextable * ObjDict2_scanIndexOD (UNS16 wIndex, UNS32 * errorCode, ODCallback_t **callbacks)
{
	int i;
	*callbacks = NULL;
	switch(wIndex){
		case 0x1000: i = 0;break;
		case 0x1001: i = 1;break;
		case 0x1005: i = 2;*callbacks = ObjDict2_Index1005_callbacks; break;
		case 0x1006: i = 3;*callbacks = ObjDict2_Index1006_callbacks; break;
		case 0x1016: i = 4;break;
		case 0x1018: i = 5;break;
		case 0x1200: i = 6;break;
		case 0x1280: i = 7;break;
		case 0x1400: i = 8;break;
		case 0x1600: i = 9;break;
		case 0x1800: i = 10;*callbacks = ObjDict2_Index1800_callbacks; break;
		case 0x1A00: i = 11;break;
		case 0x2000: i = 12;break;
		case 0x2001: i = 13;break;
		case 0x2100: i = 14;break;
		case 0x2101: i = 15;break;
		default:
			*errorCode = OD_NO_SUCH_OBJECT;
			return NULL;
	}
	*errorCode = OD_SUCCESSFUL;
	return &ObjDict2_objdict[i];
}

/* 
 * To count at which received SYNC a PDO must be sent.
 * Even if no pdoTransmit are defined, at least one entry is computed
 * for compilations issues.
 */
s_PDO_status ObjDict2_PDO_status[1] = {s_PDO_status_Initializer};

quick_index ObjDict2_firstIndex = {
  6, /* SDO_SVR */
  7, /* SDO_CLT */
  8, /* PDO_RCV */
  9, /* PDO_RCV_MAP */
  10, /* PDO_TRS */
  11 /* PDO_TRS_MAP */
};

quick_index ObjDict2_lastIndex = {
  6, /* SDO_SVR */
  7, /* SDO_CLT */
  8, /* PDO_RCV */
  9, /* PDO_RCV_MAP */
  10, /* PDO_TRS */
  11 /* PDO_TRS_MAP */
};

UNS16 ObjDict2_ObjdictSize = sizeof(ObjDict2_objdict)/sizeof(ObjDict2_objdict[0]); 

CO_Data ObjDict2_Data = CANOPEN_NODE_DATA_INITIALIZER(ObjDict2);

