
/* File generated by gen_cfile.py. Should not be modified. */

#include "ObjDict1.h"

/**************************************************************************/
/* Declaration of the mapped variables                                    */
/**************************************************************************/
UNS8 DI1 = 0x20;		/* Mapped at index 0x2000, subindex 0x00 */
UNS8 DI2 = 0x40;		/* Mapped at index 0x2001, subindex 0x00 */
UNS8 DO1 = 0x60;		/* Mapped at index 0x2100, subindex 0x00 */
UNS8 DO2 = 0x80;		/* Mapped at index 0x2101, subindex 0x00 */

/**************************************************************************/
/* Declaration of the value range types                                   */
/**************************************************************************/

#define valueRange_EMC 0x9F /* Type for index 0x1003 subindex 0x00 (only set of value 0 is possible) */
UNS32 ObjDict1_valueRangeTest (UNS8 typeValue, void * value)
{
  switch (typeValue) {
    case valueRange_EMC:
      if (*(UNS8*)value != (UNS8)0) return OD_VALUE_RANGE_EXCEEDED;
      break;
  }
  return 0;
}

/**************************************************************************/
/* The node id                                                            */
/**************************************************************************/
/* node_id default value.*/
UNS8 ObjDict1_bDeviceNodeId = 0x00;

/**************************************************************************/
/* Array of message processing information */

const UNS8 ObjDict1_iam_a_slave = 1;

TIMER_HANDLE ObjDict1_heartBeatTimers[1] = {TIMER_NONE};

/*
$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$

                               OBJECT DICTIONARY

$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
*/

/* index 0x1000 :   Device Type. */
                    UNS32 ObjDict1_obj1000 = 0x12345;	/* 197009 */
                    subindex ObjDict1_Index1000[] = 
                     {
                       { RO, uint32, sizeof (UNS32), (void*)&ObjDict1_obj1000 }
                     };

/* index 0x1001 :   Error Register. */
                    UNS8 ObjDict1_obj1001 = 0x0;	/* 0 */
                    subindex ObjDict1_Index1001[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&ObjDict1_obj1001 }
                     };

/* index 0x1003 :   Pre-defined Error Field */
                    UNS8 ObjDict1_highestSubIndex_obj1003 = 0; /* number of subindex - 1*/
                    UNS32 ObjDict1_obj1003[] = 
                    {
                      0x0	/* 0 */
                    };
                    ODCallback_t ObjDict1_Index1003_callbacks[] = 
                     {
                       NULL,
                       NULL,
                     };
                    subindex ObjDict1_Index1003[] = 
                     {
                       { RW, valueRange_EMC, sizeof (UNS8), (void*)&ObjDict1_highestSubIndex_obj1003 },
                       { RO, uint32, sizeof (UNS32), (void*)&ObjDict1_obj1003[0] }
                     };

/* index 0x1005 :   SYNC COB ID. */
                    UNS32 ObjDict1_obj1005 = 0x40000080;	/* 1073741952 */
                    ODCallback_t ObjDict1_Index1005_callbacks[] = 
                     {
                       NULL,
                     };
                    subindex ObjDict1_Index1005[] = 
                     {
                       { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj1005 }
                     };

/* index 0x1006 :   Communication / Cycle Period. */
                    //UNS32 ObjDict_obj1006 = 0xF4240;	/* 1000000 */
					UNS32 ObjDict1_obj1006 = 4000000;
                    ODCallback_t ObjDict1_Index1006_callbacks[] = 
                     {
                       NULL,
                     };
                    subindex ObjDict1_Index1006[] = 
                     {
                       { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj1006 }
                     };

/* index 0x1014 :   Emergency COB ID */
                    UNS32 ObjDict1_obj1014 = 0x0;   /* 0 */

/* index 0x1016 :   Consumer Heartbeat Time. */
                    UNS8 ObjDict1_highestSubIndex_obj1016 = 1; /* number of subindex - 1*/
                    UNS32 ObjDict1_obj1016[] = 
                    {
                      0x4005DC	/* 4195804 */
                    };
                    subindex ObjDict1_Index1016[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&ObjDict1_highestSubIndex_obj1016 },
                       { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj1016[0] }
                     };

/* index 0x1017 :   Producer Heartbeat Time */ 
                    UNS16 ObjDict1_obj1017 = 0x8000;   /* 0 */

/* index 0x1018 :   Identity. */
                    UNS8 ObjDict1_highestSubIndex_obj1018 = 4; /* number of subindex - 1*/
                    UNS32 ObjDict1_obj1018_Vendor_ID = 0x1;	/* 0 */
                    UNS32 ObjDict1_obj1018_Product_Code = 0x2;	/* 0 */
                    UNS32 ObjDict1_obj1018_Revision_Number = 0x3;	/* 0 */
                    UNS32 ObjDict1_obj1018_Serial_Number = 0x4;	/* 0 */
                    subindex ObjDict1_Index1018[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&ObjDict1_highestSubIndex_obj1018 },
                       { RO, uint32, sizeof (UNS32), (void*)&ObjDict1_obj1018_Vendor_ID },
                       { RO, uint32, sizeof (UNS32), (void*)&ObjDict1_obj1018_Product_Code },
                       { RO, uint32, sizeof (UNS32), (void*)&ObjDict1_obj1018_Revision_Number },
                       { RO, uint32, sizeof (UNS32), (void*)&ObjDict1_obj1018_Serial_Number }
                     };

/* index 0x1200 :   Server SDO Parameter. */
                    UNS8 ObjDict1_highestSubIndex_obj1200 = 2; /* number of subindex - 1*/
                    UNS32 ObjDict1_obj1200_COB_ID_Client_to_Server_Receive_SDO = 0x607;	/* 1536 */
                    UNS32 ObjDict1_obj1200_COB_ID_Server_to_Client_Transmit_SDO = 0x587;	/* 1408 */
                    subindex ObjDict1_Index1200[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&ObjDict1_highestSubIndex_obj1200 },
                       { RO, uint32, sizeof (UNS32), (void*)&ObjDict1_obj1200_COB_ID_Client_to_Server_Receive_SDO },
                       { RO, uint32, sizeof (UNS32), (void*)&ObjDict1_obj1200_COB_ID_Server_to_Client_Transmit_SDO }
                     };

/* index 0x1280 :   Client SDO 1 Parameter. */
                    UNS8 ObjDict1_highestSubIndex_obj1280 = 3; /* number of subindex - 1*/
                    UNS32 ObjDict1_obj1280_COB_ID_Client_to_Server_Transmit_SDO = 0x604;	/* 1600 */
                    UNS32 ObjDict1_obj1280_COB_ID_Server_to_Client_Receive_SDO = 0x584;	/* 1472 */
                    UNS8 ObjDict1_obj1280_Node_ID_of_the_SDO_Server = 0x04;	/* 4 */
                    subindex ObjDict1_Index1280[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&ObjDict1_highestSubIndex_obj1280 },
                       { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj1280_COB_ID_Client_to_Server_Transmit_SDO },
                       { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj1280_COB_ID_Server_to_Client_Receive_SDO },
                       { RW, uint8, sizeof (UNS8), (void*)&ObjDict1_obj1280_Node_ID_of_the_SDO_Server }
                     };
/* index 0x1281 :   Client SDO 2 Parameter. */
                    UNS8 ObjDict1_highestSubIndex_obj1281 = 3; /* number of subindex - 1*/
                    UNS32 ObjDict1_obj1281_COB_ID_Client_to_Server_Transmit_SDO = 0x605;	/*  */
                    UNS32 ObjDict1_obj1281_COB_ID_Server_to_Client_Receive_SDO = 0x585;	/*  */
                    UNS8 ObjDict1_obj1281_Node_ID_of_the_SDO_Server = 0x05;	/* 5 */
                    subindex ObjDict1_Index1281[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&ObjDict1_highestSubIndex_obj1281 },
                       { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj1281_COB_ID_Client_to_Server_Transmit_SDO },
                       { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj1281_COB_ID_Server_to_Client_Receive_SDO },
                       { RW, uint8, sizeof (UNS8), (void*)&ObjDict1_obj1281_Node_ID_of_the_SDO_Server }
                     };

/* index 0x1400 :   Receive PDO 1 Parameter. */
                    UNS8 ObjDict1_highestSubIndex_obj1400 = 5; /* number of subindex - 1*/
                    UNS32 ObjDict1_obj1400_COB_ID_used_by_PDO = 0x181;	/* 385 */
                    UNS8 ObjDict1_obj1400_Transmission_Type = 0x1;	/* 1 */
                    UNS16 ObjDict1_obj1400_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 ObjDict1_obj1400_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 ObjDict1_obj1400_Event_Timer = 0x0;	/* 0 */
                    subindex ObjDict1_Index1400[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&ObjDict1_highestSubIndex_obj1400 },
                       { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj1400_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&ObjDict1_obj1400_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&ObjDict1_obj1400_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&ObjDict1_obj1400_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&ObjDict1_obj1400_Event_Timer }
                     };

/* index 0x1600 :   Receive PDO 1 Mapping. */
                    UNS8 ObjDict1_highestSubIndex_obj1600 = 1; /* number of subindex - 1*/
                    UNS32 ObjDict1_obj1600[] = 
                    {
                      0x20000008	/* 536870920 */
                    };
                    subindex ObjDict1_Index1600[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&ObjDict1_highestSubIndex_obj1600 },
                       { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj1600[0] }
                     };

/* index 0x1800 :   Transmit PDO 1 Parameter. */
                    UNS8 ObjDict1_highestSubIndex_obj1800 = 5; /* number of subindex - 1*/
                    UNS32 ObjDict1_obj1800_COB_ID_used_by_PDO = 0x201;	/* 513 */
                    UNS8 ObjDict1_obj1800_Transmission_Type = 0xFF;	
                    UNS16 ObjDict1_obj1800_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 ObjDict1_obj1800_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 ObjDict1_obj1800_Event_Timer = 0x0;	/* 0 */
                    ODCallback_t ObjDict1_Index1800_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                     };
                    subindex ObjDict1_Index1800[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&ObjDict1_highestSubIndex_obj1800 },
                       { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj1800_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&ObjDict1_obj1800_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&ObjDict1_obj1800_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&ObjDict1_obj1800_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&ObjDict1_obj1800_Event_Timer }
                     };

/* index 0x1A00 :   Transmit PDO 1 Mapping. */
                    UNS8 ObjDict1_highestSubIndex_obj1A00 = 1; /* number of subindex - 1*/
                    UNS32 ObjDict1_obj1A00[] = 
                    {
                      0x21000008	/* 553648136 */
                    };
                    subindex ObjDict1_Index1A00[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&ObjDict1_highestSubIndex_obj1A00 },
                       { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj1A00[0] }
                     };

/* index 0x2000 :   Mapped variable DI1 */
                    subindex ObjDict1_Index2000[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&DI1 }
                     };

/* index 0x2001 :   Mapped variable DI2 */
                    subindex ObjDict1_Index2001[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&DI2 }
                     };

/* index 0x2100 :   Mapped variable DO1 */
                    subindex ObjDict1_Index2100[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&DO1 }
                     };

/* index 0x2101 :   Mapped variable DO2 */
                    subindex ObjDict1_Index2101[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&DO2 }
                     };
/* index 0x2200 :   Mapped variable ... */										 
                    UNS8 ObjDict1_highestSubIndex_obj2200 = 28; /* number of subindex - 1*/
                    UNS32 ObjDict1_obj2200[] = 
                    {
                      1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28
                    };
                    subindex ObjDict1_Index2200[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&ObjDict1_highestSubIndex_obj2200 },
                       { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj2200[0] },
											 { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj2200[1] },
											 { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj2200[2] },
											 { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj2200[3] },
											 { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj2200[4] },
											 { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj2200[5] },
											 { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj2200[6] },
											 { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj2200[7] },
											 { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj2200[8] },
											 { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj2200[9] },
											 { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj2200[10] },
											 { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj2200[11] },
											 { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj2200[12] },
											 { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj2200[13] },
											 { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj2200[14] },
											 { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj2200[15] },
											 { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj2200[16] },
											 { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj2200[17] },
											 { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj2200[18] },
											 { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj2200[19] },
											 { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj2200[20] },
											 { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj2200[21] },
											 { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj2200[22] },
											 { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj2200[23] },
											 { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj2200[24] },
											 { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj2200[25] },
											 { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj2200[26] },
											 { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj2200[27] }
                     };
/* index 0x2201 :   Mapped variable ... */										 
                    UNS8 ObjDict1_highestSubIndex_obj2201 = 28; /* number of subindex - 1*/
                    UNS32 ObjDict1_obj2201[] = 
                    {
                      1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28
                    };
                    subindex ObjDict1_Index2201[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&ObjDict1_highestSubIndex_obj2201 },
                       { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj2201[0] },
											 { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj2201[1] },
											 { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj2201[2] },
											 { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj2201[3] },
											 { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj2201[4] },
											 { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj2201[5] },
											 { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj2201[6] },
											 { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj2201[7] },
											 { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj2201[8] },
											 { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj2201[9] },
											 { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj2201[10] },
											 { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj2201[11] },
											 { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj2201[12] },
											 { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj2201[13] },
											 { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj2201[14] },
											 { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj2201[15] },
											 { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj2201[16] },
											 { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj2201[17] },
											 { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj2201[18] },
											 { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj2201[19] },
											 { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj2201[20] },
											 { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj2201[21] },
											 { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj2201[22] },
											 { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj2201[23] },
											 { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj2201[24] },
											 { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj2201[25] },
											 { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj2201[26] },
											 { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj2201[27] }
                     };

/* index 0x2202 :   Mapped variable ... */										 
                    UNS8 ObjDict1_highestSubIndex_obj2202 = 28; /* number of subindex - 1*/
                    UNS32 ObjDict1_obj2202[] = 
                    {
                      1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28
                    };
                    subindex ObjDict1_Index2202[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&ObjDict1_highestSubIndex_obj2202 },
                       { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj2202[0] },
											 { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj2202[1] },
											 { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj2202[2] },
											 { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj2202[3] },
											 { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj2202[4] },
											 { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj2202[5] },
											 { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj2202[6] },
											 { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj2202[7] },
											 { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj2202[8] },
											 { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj2202[9] },
											 { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj2202[10] },
											 { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj2202[11] },
											 { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj2202[12] },
											 { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj2202[13] },
											 { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj2202[14] },
											 { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj2202[15] },
											 { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj2202[16] },
											 { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj2202[17] },
											 { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj2202[18] },
											 { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj2202[19] },
											 { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj2202[20] },
											 { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj2202[21] },
											 { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj2202[22] },
											 { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj2202[23] },
											 { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj2202[24] },
											 { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj2202[25] },
											 { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj2202[26] },
											 { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj2202[27] }
                     };

/* index 0x2203 :   Mapped variable ... */										 
                    UNS8 ObjDict1_highestSubIndex_obj2203 = 28; /* number of subindex - 1*/
                    UNS32 ObjDict1_obj2203[] = 
                    {
                      1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28
                    };
                    subindex ObjDict1_Index2203[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&ObjDict1_highestSubIndex_obj2203 },
                       { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj2203[0] },
											 { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj2203[1] },
											 { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj2203[2] },
											 { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj2203[3] },
											 { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj2203[4] },
											 { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj2203[5] },
											 { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj2203[6] },
											 { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj2203[7] },
											 { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj2203[8] },
											 { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj2203[9] },
											 { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj2203[10] },
											 { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj2203[11] },
											 { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj2203[12] },
											 { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj2203[13] },
											 { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj2203[14] },
											 { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj2203[15] },
											 { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj2203[16] },
											 { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj2203[17] },
											 { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj2203[18] },
											 { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj2203[19] },
											 { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj2203[20] },
											 { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj2203[21] },
											 { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj2203[22] },
											 { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj2203[23] },
											 { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj2203[24] },
											 { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj2203[25] },
											 { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj2203[26] },
											 { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj2203[27] }
                     };
										 
/* index 0x2204 :   Mapped variable ... */										 
                    UNS8 ObjDict1_highestSubIndex_obj2204 = 28; /* number of subindex - 1*/
                    UNS32 ObjDict1_obj2204[] = 
                    {
                      1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28
                    };
                    subindex ObjDict1_Index2204[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&ObjDict1_highestSubIndex_obj2204 },
                       { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj2204[0] },
											 { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj2204[1] },
											 { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj2204[2] },
											 { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj2204[3] },
											 { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj2204[4] },
											 { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj2204[5] },
											 { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj2204[6] },
											 { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj2204[7] },
											 { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj2204[8] },
											 { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj2204[9] },
											 { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj2204[10] },
											 { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj2204[11] },
											 { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj2204[12] },
											 { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj2204[13] },
											 { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj2204[14] },
											 { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj2204[15] },
											 { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj2204[16] },
											 { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj2204[17] },
											 { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj2204[18] },
											 { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj2204[19] },
											 { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj2204[20] },
											 { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj2204[21] },
											 { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj2204[22] },
											 { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj2204[23] },
											 { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj2204[24] },
											 { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj2204[25] },
											 { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj2204[26] },
											 { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj2204[27] }
                     };

/* index 0x2205 :   Mapped variable ... */										 
                    UNS8 ObjDict1_highestSubIndex_obj2205 = 28; /* number of subindex - 1*/
                    UNS32 ObjDict1_obj2205[] = 
                    {
                      1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28
                    };
                    subindex ObjDict1_Index2205[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&ObjDict1_highestSubIndex_obj2205 },
                       { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj2205[0] },
											 { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj2205[1] },
											 { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj2205[2] },
											 { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj2205[3] },
											 { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj2205[4] },
											 { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj2205[5] },
											 { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj2205[6] },
											 { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj2205[7] },
											 { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj2205[8] },
											 { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj2205[9] },
											 { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj2205[10] },
											 { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj2205[11] },
											 { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj2205[12] },
											 { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj2205[13] },
											 { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj2205[14] },
											 { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj2205[15] },
											 { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj2205[16] },
											 { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj2205[17] },
											 { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj2205[18] },
											 { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj2205[19] },
											 { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj2205[20] },
											 { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj2205[21] },
											 { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj2205[22] },
											 { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj2205[23] },
											 { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj2205[24] },
											 { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj2205[25] },
											 { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj2205[26] },
											 { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj2205[27] }
                     };

/* index 0x2206 :   Mapped variable ... */										 
                    UNS8 ObjDict1_highestSubIndex_obj2206 = 16; /* number of subindex - 1*/
                    UNS32 ObjDict1_obj2206[] = 
                    {
                      1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16
                    };
                    subindex ObjDict1_Index2206[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&ObjDict1_highestSubIndex_obj2206 },
                       { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj2206[0] },
											 { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj2206[1] },
											 { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj2206[2] },
											 { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj2206[3] },
											 { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj2206[4] },
											 { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj2206[5] },
											 { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj2206[6] },
											 { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj2206[7] },
											 { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj2206[8] },
											 { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj2206[9] },
											 { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj2206[10] },
											 { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj2206[11] },
											 { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj2206[12] },
											 { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj2206[13] },
											 { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj2206[14] },
											 { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj2206[15] }
                     };

/* index 0x2207 :   Mapped variable ... */										 
                    UNS8 ObjDict1_highestSubIndex_obj2207 = 16; /* number of subindex - 1*/
                    UNS32 ObjDict1_obj2207[] = 
                    {
                      1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16
                    };
                    subindex ObjDict1_Index2207[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&ObjDict1_highestSubIndex_obj2207 },
                       { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj2207[0] },
											 { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj2207[1] },
											 { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj2207[2] },
											 { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj2207[3] },
											 { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj2207[4] },
											 { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj2207[5] },
											 { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj2207[6] },
											 { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj2207[7] },
											 { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj2207[8] },
											 { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj2207[9] },
											 { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj2207[10] },
											 { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj2207[11] },
											 { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj2207[12] },
											 { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj2207[13] },
											 { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj2207[14] },
											 { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj2207[15] }
                     };
/* index 0x2208 :   Mapped variable ... */										 
                    UNS8 ObjDict1_highestSubIndex_obj2208 = 18; /* number of subindex - 1*/
                    UNS32 ObjDict1_obj2208[] = 
                    {
                      0x01080A0C,
											0x20222328,
											0x32333839,
											0x5A5B5B5E,
											0x68686A6B,
											0x72727373,
											0x75767778,
											0x80807978,
											0x7776706C,
											0x6B6B6864,
											0x62605D5C,
											0x5857504F,
											0x4C4B4844,
											0x43403F3E,
											0x3C3B3937,
											0x37333230,
											0x2B292720,
											0x16100802
                    };
                    subindex ObjDict1_Index2208[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&ObjDict1_highestSubIndex_obj2208 },
                       { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj2208[0] },
											 { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj2208[1] },
											 { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj2208[2] },
											 { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj2208[3] },
											 { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj2208[4] },
											 { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj2208[5] },
											 { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj2208[6] },
											 { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj2208[7] },
											 { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj2208[8] },
											 { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj2208[9] },
											 { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj2208[10] },
											 { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj2208[11] },
											 { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj2208[12] },
											 { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj2208[13] },
											 { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj2208[14] },
											 { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj2208[15] },
											 { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj2208[16] },
											 { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj2208[17] }
                     };

/* index 0x2209 :   Mapped variable ... */										 
                    UNS8 ObjDict1_highestSubIndex_obj2209 = 18; /* number of subindex - 1*/
                    UNS32 ObjDict1_obj2209[] = 
                    {
                      0x01020304,
											0x05050606,
											0x07070808,
											0x090A0B0C,
											0x0D0D1010,
											0x12121616,
											0x17192223,
											0x23253034,
											0x40393832,
											0x30282727,
											0x25242320,
											0x18171615,
											0x14141312,
											0x12111009,
											0x09080707,
											0x06060404,
											0x03030201,
											0x01010101
                    };
                    subindex ObjDict1_Index2209[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&ObjDict1_highestSubIndex_obj2209 },
                       { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj2209[0] },
											 { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj2209[1] },
											 { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj2209[2] },
											 { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj2209[3] },
											 { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj2209[4] },
											 { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj2209[5] },
											 { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj2209[6] },
											 { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj2209[7] },
											 { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj2209[8] },
											 { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj2209[9] },
											 { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj2209[10] },
											 { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj2209[11] },
											 { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj2209[12] },
											 { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj2209[13] },
											 { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj2209[14] },
											 { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj2209[15] },
											 { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj2209[16] },
											 { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj2209[17] }
                     };

/* index 0x220A :   Mapped variable ... */										 
                    UNS8 ObjDict1_highestSubIndex_obj220A = 3; /* number of subindex - 1*/
                    UNS32 ObjDict1_obj220A[] = 
                    {
                      1,2,3
                    };
                    subindex ObjDict1_Index220A[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&ObjDict1_highestSubIndex_obj220A },
                       { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj220A[0] },
											 { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj220A[1] },
											 { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj220A[2] }
                     };

/* index 0x220B :   Mapped variable ... */										 
                    UNS8 ObjDict1_highestSubIndex_obj220B = 3; /* number of subindex - 1*/
                    UNS32 ObjDict1_obj220B[] = 
                    {
                      1,2,3
                    };
                    subindex ObjDict1_Index220B[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&ObjDict1_highestSubIndex_obj220B },
                       { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj220B[0] },
											 { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj220B[1] },
											 { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj220B[2] }
                     };

/* index 0x2210 :   Mapped variable ... */										 
                    UNS8 ObjDict1_highestSubIndex_obj2210 = 1; /* number of subindex - 1*/
                    UNS32 ObjDict1_obj2210[] = 
                    {
                      0x0
                    };
                    subindex ObjDict1_Index2210[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&ObjDict1_highestSubIndex_obj2210 },
                       { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj2210[0] }
                     };

/* index 0x2211 :   Mapped variable ... */										 
                    UNS8 ObjDict1_highestSubIndex_obj2211 = 1; /* number of subindex - 1*/
                    UNS32 ObjDict1_obj2211[] = 
                    {
                      0x0
                    };
                    subindex ObjDict1_Index2211[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&ObjDict1_highestSubIndex_obj2211 },
                       { RW, uint32, sizeof (UNS32), (void*)&ObjDict1_obj2211[0] }
                     };
										 
										 
										 const indextable ObjDict1_objdict[] = 
{
  { (subindex*)ObjDict1_Index1000,sizeof(ObjDict1_Index1000)/sizeof(ObjDict1_Index1000[0]), 0x1000},
  { (subindex*)ObjDict1_Index1001,sizeof(ObjDict1_Index1001)/sizeof(ObjDict1_Index1001[0]), 0x1001},
  { (subindex*)ObjDict1_Index1005,sizeof(ObjDict1_Index1005)/sizeof(ObjDict1_Index1005[0]), 0x1005},
  { (subindex*)ObjDict1_Index1006,sizeof(ObjDict1_Index1006)/sizeof(ObjDict1_Index1006[0]), 0x1006},
  { (subindex*)ObjDict1_Index1016,sizeof(ObjDict1_Index1016)/sizeof(ObjDict1_Index1016[0]), 0x1016},
  { (subindex*)ObjDict1_Index1018,sizeof(ObjDict1_Index1018)/sizeof(ObjDict1_Index1018[0]), 0x1018},
  { (subindex*)ObjDict1_Index1200,sizeof(ObjDict1_Index1200)/sizeof(ObjDict1_Index1200[0]), 0x1200},
  { (subindex*)ObjDict1_Index1280,sizeof(ObjDict1_Index1280)/sizeof(ObjDict1_Index1280[0]), 0x1280},
  { (subindex*)ObjDict1_Index1281,sizeof(ObjDict1_Index1281)/sizeof(ObjDict1_Index1281[0]), 0x1280},
  { (subindex*)ObjDict1_Index1400,sizeof(ObjDict1_Index1400)/sizeof(ObjDict1_Index1400[0]), 0x1400},
  { (subindex*)ObjDict1_Index1600,sizeof(ObjDict1_Index1600)/sizeof(ObjDict1_Index1600[0]), 0x1600},
  { (subindex*)ObjDict1_Index1800,sizeof(ObjDict1_Index1800)/sizeof(ObjDict1_Index1800[0]), 0x1800},
  { (subindex*)ObjDict1_Index1A00,sizeof(ObjDict1_Index1A00)/sizeof(ObjDict1_Index1A00[0]), 0x1A00},
  { (subindex*)ObjDict1_Index2000,sizeof(ObjDict1_Index2000)/sizeof(ObjDict1_Index2000[0]), 0x2000},
  { (subindex*)ObjDict1_Index2001,sizeof(ObjDict1_Index2001)/sizeof(ObjDict1_Index2001[0]), 0x2001},
  { (subindex*)ObjDict1_Index2100,sizeof(ObjDict1_Index2100)/sizeof(ObjDict1_Index2100[0]), 0x2100},
  { (subindex*)ObjDict1_Index2101,sizeof(ObjDict1_Index2101)/sizeof(ObjDict1_Index2101[0]), 0x2101},
  { (subindex*)ObjDict1_Index2200,sizeof(ObjDict1_Index2200)/sizeof(ObjDict1_Index2200[0]), 0x2200},
  { (subindex*)ObjDict1_Index2201,sizeof(ObjDict1_Index2201)/sizeof(ObjDict1_Index2201[0]), 0x2201},
  { (subindex*)ObjDict1_Index2202,sizeof(ObjDict1_Index2202)/sizeof(ObjDict1_Index2202[0]), 0x2202},
  { (subindex*)ObjDict1_Index2203,sizeof(ObjDict1_Index2203)/sizeof(ObjDict1_Index2203[0]), 0x2203},
  { (subindex*)ObjDict1_Index2204,sizeof(ObjDict1_Index2204)/sizeof(ObjDict1_Index2204[0]), 0x2204},
	{ (subindex*)ObjDict1_Index2205,sizeof(ObjDict1_Index2205)/sizeof(ObjDict1_Index2205[0]), 0x2205},
	{ (subindex*)ObjDict1_Index2206,sizeof(ObjDict1_Index2206)/sizeof(ObjDict1_Index2206[0]), 0x2206},
	{ (subindex*)ObjDict1_Index2207,sizeof(ObjDict1_Index2207)/sizeof(ObjDict1_Index2207[0]), 0x2207},
	{ (subindex*)ObjDict1_Index2208,sizeof(ObjDict1_Index2208)/sizeof(ObjDict1_Index2208[0]), 0x2208},
	{ (subindex*)ObjDict1_Index2209,sizeof(ObjDict1_Index2209)/sizeof(ObjDict1_Index2209[0]), 0x2209},
	{ (subindex*)ObjDict1_Index220A,sizeof(ObjDict1_Index220A)/sizeof(ObjDict1_Index220A[0]), 0x220A},
	{ (subindex*)ObjDict1_Index220B,sizeof(ObjDict1_Index220B)/sizeof(ObjDict1_Index220B[0]), 0x220B},
	{ (subindex*)ObjDict1_Index2210,sizeof(ObjDict1_Index2210)/sizeof(ObjDict1_Index2210[0]), 0x2210},
	{ (subindex*)ObjDict1_Index2211,sizeof(ObjDict1_Index2211)/sizeof(ObjDict1_Index2211[0]), 0x2211},
};

const indextable * ObjDict1_scanIndexOD (UNS16 wIndex, UNS32 * errorCode, ODCallback_t **callbacks)
{
	int i;
	*callbacks = NULL;
	switch(wIndex){
		case 0x1000: i = 0;break;
		case 0x1001: i = 1;break;
		case 0x1005: i = 2;*callbacks = ObjDict1_Index1005_callbacks; break;
		case 0x1006: i = 3;*callbacks = ObjDict1_Index1006_callbacks; break;
		case 0x1016: i = 4;break;
		case 0x1018: i = 5;break;
		case 0x1200: i = 6;break;
		case 0x1280: i = 7;break;
		case 0x1281: i = 8;break;
		case 0x1400: i = 9;break;
		case 0x1600: i = 10;break;
		case 0x1800: i = 11;*callbacks = ObjDict1_Index1800_callbacks; break;
		case 0x1A00: i = 12;break;
		case 0x2000: i = 13;break;
		case 0x2001: i = 14;break;
		case 0x2100: i = 15;break;
		case 0x2101: i = 16;break;
		case 0x2200: i = 17;break;
		case 0x2201: i = 18;break;
		case 0x2202: i = 19;break;
		case 0x2203: i = 20;break;
		case 0x2204: i = 21;break;
		case 0x2205: i = 22;break;
		case 0x2206: i = 23;break;
		case 0x2207: i = 24;break;
		case 0x2208: i = 25;break;
		case 0x2209: i = 26;break;
		case 0x220A: i = 27;break;
		case 0x220B: i = 28;break;
		case 0x2210: i = 29;break;
		case 0x2211: i = 30;break;
		default:
			*errorCode = OD_NO_SUCH_OBJECT;
			return NULL;
	}
	*errorCode = OD_SUCCESSFUL;
	return &ObjDict1_objdict[i];
}

/* 
 * To count at which received SYNC a PDO must be sent.
 * Even if no pdoTransmit are defined, at least one entry is computed
 * for compilations issues.
 */
s_PDO_status ObjDict1_PDO_status[1] = {s_PDO_status_Initializer};

quick_index ObjDict1_firstIndex = {
  6, /* SDO_SVR */
  7, /* SDO_CLT */
  9, /* PDO_RCV */
  10, /* PDO_RCV_MAP */
  11, /* PDO_TRS */
  12 /* PDO_TRS_MAP */
};

quick_index ObjDict1_lastIndex = {
  6, /* SDO_SVR */
  8, /* SDO_CLT */
  9, /* PDO_RCV */
  10, /* PDO_RCV_MAP */
  11, /* PDO_TRS */
  12 /* PDO_TRS_MAP */
};

UNS16 ObjDict1_ObjdictSize = sizeof(ObjDict1_objdict)/sizeof(ObjDict1_objdict[0]); 

CO_Data ObjDict1_Data = CANOPEN_NODE_DATA_INITIALIZER(ObjDict1);

